Repository Uniswap/v4-periphery, pull requests merged in 2024-06, with the labels that each got.

#130 fix tests and use BalanceDeltas
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/base/BaseLiquidityManagement.sol
  contracts/libraries/BalanceDeltaExtensionLibrary.sol
  contracts/libraries/Position.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
Labels: PosM

#126 change add liq accounting
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/BaseLiquidityManagement.sol
  contracts/interfaces/IBaseLiquidityManagement.sol
  contracts/libraries/BalanceDeltaExtensionLibrary.sol
  contracts/libraries/CurrencySenderLibrary.sol
  contracts/libraries/FeeMath.sol
  contracts/libraries/Position.sol
  contracts/types/LiquidityRange.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: PosM

#125 make deployTimestamp immutable
  contracts/hooks/examples/VolatilityOracle.sol
Labels: repo improvement

#86 feat: abstract router
  .forge-snapshots/RouterBytecode.snap
  .forge-snapshots/RouterExactIn1Hop.snap
  .forge-snapshots/RouterExactIn2Hops.snap
  .forge-snapshots/RouterExactIn3Hops.snap
  .forge-snapshots/RouterExactInputSingle.snap
  .forge-snapshots/RouterExactOut1Hop.snap
  .forge-snapshots/RouterExactOut2Hops.snap
  .forge-snapshots/RouterExactOut3Hops.snap
  .forge-snapshots/RouterExactOutputSingle.snap
  contracts/V4Router.sol
  contracts/hooks/examples/LimitOrder.sol
  contracts/interfaces/IPeripheryPayments.sol
  contracts/interfaces/IV4Router.sol
  test/FullRange.t.sol
  test/V4Router.t.sol
  test/shared/implementation/V4RouterImplementation.sol
  test/utils/HookEnabledSwapRouter.sol
Labels: Router

#133 update decrease
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/BaseLiquidityManagement.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  contracts/libraries/CurrencySenderLibrary.sol
  contracts/libraries/LiquidityDeltaAccounting.sol
  contracts/libraries/Position.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
Labels: PosM

#136 consistent return types
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/BaseLiquidityManagement.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: PosM
