Repository Uniswap/v4-periphery, pull requests merged in 2024-07, with the labels that each got.

#138 Rip Out Vanilla
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/BaseLiquidityManagement.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  contracts/libraries/TransientLiquidityDelta.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/shared/LiquidityOperations.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: PosM

#135 temp-dev-update
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mintWithLiquidity.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/BaseLiquidityManagement.sol
  contracts/interfaces/IBaseLiquidityManagement.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  contracts/libraries/LiquidityDeltaAccounting.sol
  contracts/libraries/TransientDemo.sol
  contracts/libraries/TransientLiquidityDelta.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/shared/LiquidityOperations.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: PosM

#153 Owner-level ERC721 Permit
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/collect_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mint.snap
  .forge-snapshots/mintWithLiquidity.snap
  .forge-snapshots/mint_differentRanges.snap
  .forge-snapshots/mint_same_tickLower.snap
  .forge-snapshots/mint_same_tickUpper.snap
  .forge-snapshots/permit.snap
  .forge-snapshots/permit_secondPosition.snap
  .forge-snapshots/permit_twice.snap
  .forge-snapshots/sameRange_collect.snap
  .forge-snapshots/sameRange_decreaseAllLiquidity.snap
  .forge-snapshots/sameRange_mint.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/ERC721Permit.sol
  contracts/interfaces/IBaseLiquidityManagement.sol
  contracts/interfaces/IERC721Permit.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/position-managers/Permit.t.sol
  test/shared/FeeMath.sol
  test/shared/LiquidityOperations.sol
Labels: posm

#154 Multicall & initialize
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/collect_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mint.snap
  .forge-snapshots/mintWithLiquidity.snap
  .forge-snapshots/mint_differentRanges.snap
  .forge-snapshots/mint_same_tickLower.snap
  .forge-snapshots/mint_same_tickUpper.snap
  .forge-snapshots/multicall_initialize_mint.snap
  .forge-snapshots/permit.snap
  .forge-snapshots/permit_secondPosition.snap
  .forge-snapshots/permit_twice.snap
  .forge-snapshots/sameRange_collect.snap
  .forge-snapshots/sameRange_decreaseAllLiquidity.snap
  .forge-snapshots/sameRange_mint.snap
  contracts/NonfungiblePositionManager.sol
  contracts/base/PoolInitializer.sol
  test/base/Multicall.t.sol
  test/mock/MockMulticall.sol
  test/position-managers/Gas.t.sol
  test/position-managers/Multicall.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
Labels: posm

#158 prep shared actions & move deadline
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/collect_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mint.snap
  .forge-snapshots/mint_differentRanges.snap
  .forge-snapshots/mint_same_tickLower.snap
  .forge-snapshots/mint_same_tickUpper.snap
  .forge-snapshots/multicall_initialize_mint.snap
  .forge-snapshots/sameRange_collect.snap
  .forge-snapshots/sameRange_decreaseAllLiquidity.snap
  .forge-snapshots/sameRange_mint.snap
  contracts/NonfungiblePositionManager.sol
  contracts/interfaces/INonfungiblePositionManager.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/Multicall.t.sol
  test/position-managers/NonfungiblePositionManager.t.sol
  test/position-managers/Permit.t.sol
  test/shared/LiquidityOperations.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: posm

#161 ERC721Permit cleanup
  .forge-snapshots/autocompound_exactUnclaimedFees.snap
  .forge-snapshots/autocompound_exactUnclaimedFees_exactCustodiedFees.snap
  .forge-snapshots/autocompound_excessFeesCredit.snap
  .forge-snapshots/collect_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc20.snap
  .forge-snapshots/decreaseLiquidity_erc6909.snap
  .forge-snapshots/increaseLiquidity_erc20.snap
  .forge-snapshots/increaseLiquidity_erc6909.snap
  .forge-snapshots/mint.snap
  .forge-snapshots/mint_differentRanges.snap
  .forge-snapshots/mint_same_tickLower.snap
  .forge-snapshots/mint_same_tickUpper.snap
  .forge-snapshots/multicall_initialize_mint.snap
  .forge-snapshots/permit.snap
  .forge-snapshots/permit_secondPosition.snap
  .forge-snapshots/permit_twice.snap
  .forge-snapshots/sameRange_collect.snap
  .forge-snapshots/sameRange_decreaseAllLiquidity.snap
  .forge-snapshots/sameRange_mint.snap
  src/NonfungiblePositionManager.sol
  src/base/ERC721Permit.sol
  src/interfaces/INonfungiblePositionManager.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/Gas.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/Multicall.t.sol
  test/shared/FeeMath.sol
  test/shared/LiquidityOperations.sol
  test/shared/fuzz/LiquidityFuzzers.sol
  test/utils/Planner.sol
Labels: posm

#189 posm: Native Token
  .forge-snapshots/PositionManager_collect.snap
  .forge-snapshots/PositionManager_collect_native.snap
  .forge-snapshots/PositionManager_collect_sameRange.snap
  .forge-snapshots/PositionManager_decreaseLiquidity.snap
  .forge-snapshots/PositionManager_decreaseLiquidity_native.snap
  .forge-snapshots/PositionManager_decrease_sameRange_allLiquidity.snap
  .forge-snapshots/PositionManager_increaseLiquidity_erc20.snap
  .forge-snapshots/PositionManager_increaseLiquidity_native.snap
  .forge-snapshots/PositionManager_increase_autocompoundExactUnclaimedFees.snap
  .forge-snapshots/PositionManager_increase_autocompoundExcessFeesCredit.snap
  .forge-snapshots/PositionManager_mint.snap
  .forge-snapshots/PositionManager_mint_native.snap
  .forge-snapshots/PositionManager_mint_nativeWithSweep.snap
  .forge-snapshots/PositionManager_mint_onSameTickLower.snap
  .forge-snapshots/PositionManager_mint_onSameTickUpper.snap
  .forge-snapshots/PositionManager_mint_sameRange.snap
  .forge-snapshots/PositionManager_mint_warmedPool_differentRange.snap
  .forge-snapshots/PositionManager_multicall_initialize_mint.snap
  src/PositionManager.sol
  src/interfaces/IPositionManager.sol
  test/position-managers/Gas.t.sol
  test/position-managers/NativeToken.t.sol
  test/shared/LiquidityOperations.sol
Labels: posm

#58 Routing
  .forge-snapshots/BaseActionsRouter_mock10commands.snap
  .forge-snapshots/V4Router_Bytecode.snap
  .forge-snapshots/V4Router_ExactIn1Hop_oneForZero.snap
  .forge-snapshots/V4Router_ExactIn1Hop_zeroForOne.snap
  .forge-snapshots/V4Router_ExactIn2Hops.snap
  .forge-snapshots/V4Router_ExactIn3Hops.snap
  .forge-snapshots/V4Router_ExactInputSingle.snap
  .forge-snapshots/V4Router_ExactOut1Hop_oneForZero.snap
  .forge-snapshots/V4Router_ExactOut1Hop_zeroForOne.snap
  .forge-snapshots/V4Router_ExactOut2Hops.snap
  .forge-snapshots/V4Router_ExactOut3Hops.snap
  .forge-snapshots/V4Router_ExactOutputSingle.snap
  src/V4Router.sol
  src/base/BaseActionsRouter.sol
  src/base/DeltaResolver.sol
  src/interfaces/IV4Router.sol
  src/libraries/Actions.sol
  src/libraries/PathKey.sol
  src/libraries/SafeCast.sol
  test/BaseActionsRouter.t.sol
  test/Quoter.t.sol
  test/mocks/MockBaseActionsRouter.sol
  test/position-managers/PositionManager.gas.t.sol
  test/router/V4Router.gas.t.sol
  test/router/V4Router.t.sol
  test/shared/ActionsRouterPlanner.sol
  test/shared/RoutingTestHelpers.sol
  test/shared/implementation/V4RouterImplementation.sol
Labels: Router

#214 posm : use actions router, remove return vals
  .forge-snapshots/PositionManager_burn_empty.snap
  .forge-snapshots/PositionManager_burn_empty_native.snap
  .forge-snapshots/PositionManager_burn_nonEmpty.snap
  .forge-snapshots/PositionManager_burn_nonEmpty_native.snap
  .forge-snapshots/PositionManager_collect.snap
  .forge-snapshots/PositionManager_collect_native.snap
  .forge-snapshots/PositionManager_collect_sameRange.snap
  .forge-snapshots/PositionManager_decreaseLiquidity.snap
  .forge-snapshots/PositionManager_decreaseLiquidity_native.snap
  .forge-snapshots/PositionManager_decrease_burnEmpty.snap
  .forge-snapshots/PositionManager_decrease_burnEmpty_native.snap
  .forge-snapshots/PositionManager_decrease_sameRange_allLiquidity.snap
  .forge-snapshots/PositionManager_increaseLiquidity_erc20.snap
  .forge-snapshots/PositionManager_increaseLiquidity_native.snap
  .forge-snapshots/PositionManager_increase_autocompoundExactUnclaimedFees.snap
  .forge-snapshots/PositionManager_increase_autocompoundExcessFeesCredit.snap
  .forge-snapshots/PositionManager_mint.snap
  .forge-snapshots/PositionManager_mint_native.snap
  .forge-snapshots/PositionManager_mint_nativeWithSweep.snap
  .forge-snapshots/PositionManager_mint_onSameTickLower.snap
  .forge-snapshots/PositionManager_mint_onSameTickUpper.snap
  .forge-snapshots/PositionManager_mint_sameRange.snap
  .forge-snapshots/PositionManager_mint_warmedPool_differentRange.snap
  .forge-snapshots/PositionManager_multicall_initialize_mint.snap
  src/PositionManager.sol
  src/base/BaseActionsRouter.sol
  src/interfaces/IPositionManager.sol
  src/libraries/Actions.sol
  test/BaseActionsRouter.t.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/NativeToken.t.sol
  test/position-managers/PositionManager.gas.t.sol
  test/position-managers/PositionManager.multicall.t.sol
  test/position-managers/PositionManager.t.sol
  test/router/V4Router.gas.t.sol
  test/router/V4Router.t.sol
  test/shared/ActionsRouterPlanner.sol
  test/shared/HookSavesDelta.sol
  test/shared/LiquidityOperations.sol
  test/shared/Planner.sol
  test/shared/PosmTestSetup.sol
  test/shared/RoutingTestHelpers.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: posm

#194 some posm tests
  .forge-snapshots/PositionManager_burn_empty.snap
  .forge-snapshots/PositionManager_burn_empty_native.snap
  .forge-snapshots/PositionManager_burn_nonEmpty.snap
  .forge-snapshots/PositionManager_burn_nonEmpty_native.snap
  .forge-snapshots/PositionManager_decrease_burnEmpty.snap
  .forge-snapshots/PositionManager_decrease_burnEmpty_native.snap
  src/PositionManager.sol
  test/StateViewTest.t.sol
  test/position-managers/Execute.t.sol
  test/position-managers/FeeCollection.t.sol
  test/position-managers/IncreaseLiquidity.t.sol
  test/position-managers/PositionManager.gas.t.sol
  test/position-managers/PositionManager.t.sol
  test/shared/HookSavesDelta.sol
  test/shared/PosmTestSetup.sol
  test/shared/fuzz/LiquidityFuzzers.sol
Labels: posm
